### ISSUE TITLE
Do your graphics look like this?

### ISSUE THREAD

**Issue by Nutori3** [Walkedharmony/GINKA-IND#1]
It's just impossible to translate it so that the text fits into the framework
![Снимок1](https://github.com/Walkedharmony/GINKA-IND/assets/137778917/3e665653-7171-4c9b-8387-05f9b1d63503)
![Снимок](https://github.com/Walkedharmony/GINKA-IND/assets/137778917/1a6da1d4-d9c2-440b-bdc6-04c67fd323b7)

**Comment by Walkedharmony** [comment]
> Tidak mungkin menerjemahkannya sehingga teksnya sesuai dengan kerangkanya ![Catatan1](https://private-user-images.githubusercontent.com/137778917/306067812-3e665653-7171-4c9b-8387-05f9b1d63503.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MDQ0MDEsIm5iZiI6MTcwODQwNDEwMSwicGF0aCI6Ii8xMzc3Nzg5MTcvMzA2MDY3ODEyLTNlNjY1NjUzLTcxNzEtNGM5Yi04Mzg3LTA1ZjliMWQ2MzUwMy5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMFQwNDQxNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNDZiZmZiOTNjMTc1MWNmZjYwZmYwYWYxMjNmZGFlZDQxMTE2MjY0YWM4ODVmNzhhNTdmYjQzY2JjNTQyNjUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.StO7eKNIwD3U9oWM5skjVyTyUrSZnNzL0shhkv7NF9U) ![Sindiran](https://private-user-images.githubusercontent.com/137778917/306067816-1a6da1d4-d9c2-440b-bdc6-04c67fd323b7.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MDQ0MDEsIm5iZiI6MTcwODQwNDEwMSwicGF0aCI6Ii8xMzc3Nzg5MTcvMzA2MDY3ODE2LTFhNmRhMWQ0LWQ5YzItNDQwYi1iZGM2LTA0YzY3ZmQzMjNiNy5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMFQwNDQxNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYmY5YzBjZjhlYjgwNzQ0ZjIyZTg2ZjkwMzgzNjI0YzMzNWNjMmRjOTdlZWVkM2JjMmIxNmEzMWI0ZTJlNWY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8e7qTkDVA1M9bciSQEaa7BYmPwY7qMOAAwqaSpiXEEY)

Yes, my chart is like that but I didn't translate it due to limited space to change the text. 

Sorry if my language is bad

**Comment by Walkedharmony** [comment]
> It's just impossible to translate it so that the text fits into the framework ![Снимок1](https://private-user-images.githubusercontent.com/137778917/306067812-3e665653-7171-4c9b-8387-05f9b1d63503.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0NTE4NTQsIm5iZiI6MTcwODQ1MTU1NCwicGF0aCI6Ii8xMzc3Nzg5MTcvMzA2MDY3ODEyLTNlNjY1NjUzLTcxNzEtNGM5Yi04Mzg3LTA1ZjliMWQ2MzUwMy5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMFQxNzUyMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NDMyY2EyMmNhZmUyNDZhNWJiMzQ5ODZlNmFjYTQyMDEwMGExYzI5NTRhOTc0NDUxZWE4MDdkMmMxOTkzNmVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jnDUmTbwJ2RPBAD1B5sy4B0cn7hDqfXP759KpgsYYFA) ![Снимок](https://private-user-images.githubusercontent.com/137778917/306067816-1a6da1d4-d9c2-440b-bdc6-04c67fd323b7.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0NTE4NTQsIm5iZiI6MTcwODQ1MTU1NCwicGF0aCI6Ii8xMzc3Nzg5MTcvMzA2MDY3ODE2LTFhNmRhMWQ0LWQ5YzItNDQwYi1iZGM2LTA0YzY3ZmQzMjNiNy5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMFQxNzUyMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNmRhYjM1NjAyODIzODAxMDI0MGE2NDJmZGMyNjhlNWUxNGFjMWRhMjhhYTBkZjg2NGRiNGMzZjdlMjhjNjc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.38ZfeL-vObo4Xsz-m3mhFDQiorWncPayXfB8U3CYTUE)

are there any other problems?

**Comment by Nutori3** [comment]
Only that's the problem. All the others were solved back in the fall.

**Comment by Walkedharmony** [comment]
> Only that's the problem. All the others were solved back in the fall.

Alright

**Comment by Walkedharmony** [comment]
> Only that's the problem. All the others were solved back in the fall.

Did you create a language patch for GINKA? If so, what language is it?

**Comment by Nutori3** [comment]
> > Only that's the problem. All the others were solved back in the fall.
> 
> Did you create a language patch for GINKA? If so, what language is it?

In Russian. It is in the process of translation. I am not a translator, just someone who publishes progress and is responsible for the technical part with graphics. https://vndb.org/r114508
