### ISSUE TITLE
Using tutorial

### ISSUE THREAD

**Issue by Fegartyx** [Walkedharmony/GINKA-IND#2]
Hello I want to ask about your tutorial, I already got the file .log and saw it using Notepad and checked that the asset has been extracted in another folder, so you say .log file can build with GenXHashList but I don't know how to use it, any suggestion?

**Comment by Walkedharmony** [comment]
> Halo saya ingin bertanya tentang tutorial Anda, saya sudah mendapatkan file .log dan melihatnya menggunakan Notepad dan memeriksa apakah aset telah diekstraksi di folder lain, jadi Anda mengatakan file .log dapat dibangun dengan GenXHashList tetapi saya tidak tahu cara menggunakannya, ada saran?

Before that, is the visual novel you want to extract already available on regular [GarBRO](https://github.com/morkt/GARbro)? can you send the vndb link

If you are Indonesian, please use Indonesian

**Comment by Walkedharmony** [comment]
> > Halo saya ingin bertanya tentang tutorial Anda, saya sudah mendapatkan file .log dan melihatnya menggunakan Notepad dan memeriksa apakah aset telah diekstraksi di folder lain, jadi Anda mengatakan file .log dapat dibangun dengan GenXHashList tetapi saya tidak tahu cara menggunakannya, ada saran?
> 
> Before that, is the visual novel you want to extract already available on regular [GarBRO](https://github.com/morkt/GARbro)? can you send the vndb link

If you are Indonesian, please use Indonesian

**Comment by Fegartyx** [comment]
kayaknya sih belum ada di garbro regular tapi yang di mod udah ada cuman bahasa filenya masih bahasa alien gitu

**Comment by Walkedharmony** [comment]
> kayaknya sih belum ada di garbro regular tapi yang di mod udah ada cuman bahasa filenya masih bahasa alien gitu

Bisa kirim link vndb visual novelnya?

**Comment by Fegartyx** [comment]
Visual novelnya ya Ginka ini

**Comment by Walkedharmony** [comment]
> Visual novelnya ya Ginka ini

Owalah kukira Visual novel lainnya

**Comment by Fegartyx** [comment]
Kagak vn ginka itulah, ada solusinya kah?

**Comment by Walkedharmony** [comment]
> Kagak vn ginka itulah, ada solusinya kah?

Unduh program [GenHxHashList](https://github.com/crskycode/GenHxHashList) buat txt trus ganti formatnya ke .bat 

isi perintahnya seperti ini 
 
![Screenshot 2024-02-28 211211](https://github.com/Walkedharmony/GINKA-IND/assets/157404664/2c6e3c15-a049-414c-9e8a-66372ad8888c)

Hasilnya akan berupa file HxNames.lst, setelah itu copas ke direktori folder GameData [GarBRO Mod](https://github.com/crskycode/GARbro) 
![Screenshot 2024-02-28 211505](https://github.com/Walkedharmony/GINKA-IND/assets/157404664/d15a0087-dd7e-4f8d-bd91-94f0343c60f2)

Edit : Ganti nama file .log sesuai log yang udah di dumper

**Comment by Fegartyx** [comment]
Nah itu kan udah dpt .lst itu copy ke dir gamedata nya vn ginka nya ya?

**Comment by Walkedharmony** [comment]
> Nah itu kan udah dpt .lst itu copy ke dir gamedata nya vn ginka nya ya?

Ke direktori folder gamedata GarBro yang Mod linknya udah kukasih itu

**Comment by Walkedharmony** [comment]
> Nah itu kan udah dpt .lst itu copy ke dir gamedata nya vn ginka nya ya?

Jika sudah open issue akan ku tutup

**Comment by Fegartyx** [comment]
Ok tak coba dulu

**Comment by Fegartyx** [comment]
ksn udah saya coba tu dapet file .lst nya tapi filenya ukurannya 0 byte gadak isinya, apa ada yang salah dengan file .log nya? file lognya itu dapetinnya dengan mainin gamenya kan? saya maininnya udah semua story tapi saya skip

**Comment by Walkedharmony** [comment]
> ksn udah saya coba tu dapet file .lst nya tapi filenya ukurannya 0 byte gadak isinya, apa ada yang salah dengan file .log nya? file lognya itu dapetinnya dengan mainin gamenya kan? saya maininnya udah semua story tapi saya skip

Udah pakai [krkrdump](https://github.com/crskycode/KrkrDump) yang ini kan? Drag and drop exe ke krkrdump.exe meskipun pakai fitur skip tetap bisa diekstrak tapi file  .log harus di refresh setiap saat. Dan seharusnya file  .log ada isinya. Kamu bisa check isi file  .lst [disini](https://github.com/crskycode/GARbro/issues/14#issuecomment-1817729221)

**Comment by Fegartyx** [comment]
iya ada isi file .lognya 
[KrkrDump-2024-02-29.log](https://github.com/Walkedharmony/GINKA-IND/files/14441510/KrkrDump-2024-02-29.log)
tapi ya itu file .lst nya itu 0 byte

**Comment by Walkedharmony** [comment]
> iya ada isi file .lognya [KrkrDump-2024-02-29.log](https://github.com/Walkedharmony/GINKA-IND/files/14441510/KrkrDump-2024-02-29.log) tapi ya itu file .lst nya itu 0 byte

Check  .lst apa ada isinya. 

Check pendukung GenHxList, kalo gasalah butuh  .net framework 4.6

**Comment by Walkedharmony** [comment]
> iya ada isi file .lognya [KrkrDump-2024-02-29.log](https://github.com/Walkedharmony/GINKA-IND/files/14441510/KrkrDump-2024-02-29.log) tapi ya itu file .lst nya itu 0 byte

Seharusnya isi dari .log begini 
[KrkrDump-2024-01-23.log](https://github.com/Walkedharmony/GINKA-IND/files/14444234/KrkrDump-2024-01-23.log)

Coba itu build dengan GenHxHashList

**Comment by Fegartyx** [comment]
lah iya bisa ada mb filenya kok log ku gagal ya methode untuk dapetin lognya sekedar buka gamenya aja kan?

**Comment by Walkedharmony** [comment]
> lah iya bisa ada mb filenya kok log ku gagal ya methode untuk dapetin lognya sekedar buka gamenya aja kan?

Iya seharusnya begitu, setelah ku cek isi .log mu hanya menghasilkan ``Extract "appconfig.tjs"`` dan seterusnya, itu bukan hash file seharusnya keluarannya itu begini 
``NameHash: "appconfig.tjs" "xp3hnp" "5BA0F09AC06320DDC5A6ACBEBEDD832024CD075FA185D3413DFECFF0D21943ED"`` dan setelah itu baru dibawahnya itu akan ada perintah ``Extract "appconfig.tjs"``

**Comment by Fegartyx** [comment]
itu salahnya dimana ya kira2? apa karna make KrKrDump versi terbaru? v1.2

**Comment by Walkedharmony** [comment]
> itu salahnya dimana ya kira2? apa karna make KrKrDump versi terbaru? v1.2

Coba pakai .json yang ini [KrkrDump.json](https://github.com/Walkedharmony/GINKA-IND/files/14456091/KrkrDump.json) disitu ada option ``"dumpHash": true``

**Comment by Fegartyx** [comment]
iya sih gadah dumpHashnya, itu btw exlude .ogg gk di buat gk ngelag kah? aku langsung crash gamenya kalo gk di exclude file .ogg nya

**Comment by Fegartyx** [comment]
ohhh iya mas bisa harus ada dumpHash berarti ya makasi ya sukses saya tutup kalau begitu
