### ISSUE TITLE
GINKA UPDATE

### ISSUE THREAD

**Issue by Nutori3** [Walkedharmony/GINKA-IND#3]
![загруженное (95)](https://github.com/Walkedharmony/GINKA-IND/assets/137778917/bfce0c7e-4c91-4bfc-93b8-ec2b04a6ed84)

Hello. The game was updated the other day. Faced with the problem that even with 100% save can not go to this new ending. Do you have script files .scn (in pure form) for this ending?If possible, please share all the .scn files of the latest version 1.0.6 as a .zip archive

**Comment by Walkedharmony** [comment]
> ![загруженное (95)](https://private-user-images.githubusercontent.com/137778917/337547304-bfce0c7e-4c91-4bfc-93b8-ec2b04a6ed84.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NTE1MjIsIm5iZiI6MTcxNzc1MTIyMiwicGF0aCI6Ii8xMzc3Nzg5MTcvMzM3NTQ3MzA0LWJmY2UwYzdlLTRjOTEtNGJmYy05M2I4LWVjMmIwNGE2ZWQ4NC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwN1QwOTA3MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MTBjZTI0NzUyYzcwODZlY2RmZWExYWU2MDUyOTZlN2RjZDQ5MDA4ZmJiMTM5M2Y3OTZlOGJjNWU4NDRkNGEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8xn0aTjTxdQyOWSxIKc1FtS4GU-JsvTHrkBQAhNXnWY) Saya akan memeriksanya nanti dengan versi yang diperbarui juga.



> ![загруженное (95)](https://private-user-images.githubusercontent.com/137778917/337547304-bfce0c7e-4c91-4bfc-93b8-ec2b04a6ed84.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NTE1NTgsIm5iZiI6MTcxNzc1MTI1OCwicGF0aCI6Ii8xMzc3Nzg5MTcvMzM3NTQ3MzA0LWJmY2UwYzdlLTRjOTEtNGJmYy05M2I4LWVjMmIwNGE2ZWQ4NC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwN1QwOTA3MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MzVkNzZhZWY2N2VkNzBhYjJlMGQ0ZGEyYmE4M2FlNDQ5ZjRiMDU0ZWU4ZWIzZjY5MjczZmZmOTk1MTFjMTc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mqzrfbpcL8zhJLLhKYvclBLptPBo2kYwM1YLuF2DRn0)

I'll check it later with the updated version too.

**Comment by Walkedharmony** [comment]
> ![загруженное (95)](https://private-user-images.githubusercontent.com/137778917/337547304-bfce0c7e-4c91-4bfc-93b8-ec2b04a6ed84.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3ODA0MzYsIm5iZiI6MTcxNzc4MDEzNiwicGF0aCI6Ii8xMzc3Nzg5MTcvMzM3NTQ3MzA0LWJmY2UwYzdlLTRjOTEtNGJmYy05M2I4LWVjMmIwNGE2ZWQ4NC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwN1QxNzA4NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZjRmYmY3MGM0MTI1NzdkNTIwYjA1NGFjOWNhY2JlYjQ4MzkxNWJhMTZjMzQ5YmJhYTAyOTEzNGFmMjBkOGY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wwPotZUrYa1xXh392zBTZVPUAn1GlDP-HbFqAAvlaNo)
> 
> Hello. The game was updated the other day. Faced with the problem that even with 100% save can not go to this new ending. Do you have script files .scn (in pure form) for this ending?If possible, please share all the .scn files of the latest version 1.0.6 as a .zip archive

all I can say now is that maybe the dumper can't take patch_cr_data 
I've tested it several times on my dump folder there is no extraction anymore even though the game is still running on the latest version.

![Screenshot 2024-06-08 003336](https://github.com/Walkedharmony/GINKA-IND/assets/157404664/edb8db11-85da-4d67-822f-828d0450182e)

EDITED : and maybe I'm doing it wrong, because I'm using a Steam API that doesn't match the current version. 
the last problem is in the Dumper

**Comment by Walkedharmony** [comment]
> ![загруженное (95)](https://private-user-images.githubusercontent.com/137778917/337547304-bfce0c7e-4c91-4bfc-93b8-ec2b04a6ed84.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4MjAxMzksIm5iZiI6MTcxNzgxOTgzOSwicGF0aCI6Ii8xMzc3Nzg5MTcvMzM3NTQ3MzA0LWJmY2UwYzdlLTRjOTEtNGJmYy05M2I4LWVjMmIwNGE2ZWQ4NC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQwNDEwMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZmI4N2JiNmIyNWM5NTg3MTljNDlkMjA3N2Y3M2I4ZTk3YWE4Y2NhZjBmNzFiYjg0NjZmY2I2Y2QwMDNjOTViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.j5XzGRcQiacKXP0NRZfxa2zbS2arLQKyrOfC7Ub7EyA)
> 
> Hello. The game was updated the other day. Faced with the problem that even with 100% save can not go to this new ending. Do you have script files .scn (in pure form) for this ending?If possible, please share all the .scn files of the latest version 1.0.6 as a .zip archive

Additional: Dumper excludes some files from the patch content

**Comment by Nutori3** [comment]
So I understand correctly that it is impossible to access the after story file?

**Comment by Walkedharmony** [comment]
> So I understand correctly that it is impossible to access the after story file?

I just got it
[after.ks.zip](https://github.com/user-attachments/files/15749084/after.ks.zip)
